# REUSE.toml
# See spec: https://reuse.software/spec/
version = 1

############################
# General upstream defaults
############################

# Treat upstream code as MIT by default. More specific entries (for underscore
# folders below) will effectively override where needed.

# Defaults for core code
[[files]]
path = "Content.Server/**"
license = "MIT"

[[files]]
path = "Content.Client/**"
license = "MIT"

[[files]]
path = "Content.Shared/**"
license = "MIT"

[[files]]
path = ".github/**"
license = "MIT"

# Docs and tools
[[files]]
path = "Content.Docfx/**"
license = "MIT"

[[files]]
path = "Tools/**"
license = "MIT"

## LateStation code licensed under MIT OR AGPL-3.0-or-later
[[files]]
path = "Content.Server/_LateStation/**"
license = "MIT OR AGPL-3.0-or-later"

[[files]]
path = "Content.Client/_LateStation/**"
license = "MIT OR AGPL-3.0-or-later"

[[files]]
path = "Content.Shared/_LateStation/**"
license = "MIT OR AGPL-3.0-or-later"

[[files]]
path = "Resources/_LateStation/**"
license = "MIT OR AGPL-3.0-or-later"

[[files]]
path = "Resources/Prototypes/_LateStation/**"
license = "MIT OR AGPL-3.0-or-later"

## AXOLOTL code licensed under MIT
[[files]]
path = "Content.Server/_AXOLOTL/**"
license = "MIT"

[[files]]
path = "Content.Client/_AXOLOTL/**"
license = "MIT"

[[files]]
path = "Content.Shared/_AXOLOTL/**"
license = "MIT"

[[files]]
path = "Resources/_AXOLOTL/**"
license = "MIT"

[[files]]
path = "Resources/Prototypes/_AXOLOTL/**"
license = "MIT"

## CD (Cosmatic Drift) code licensed under MIT
[[files]]
path = "Content.Server/_CD/**"
license = "MIT"

[[files]]
path = "Content.Client/_CD/**"
license = "MIT"

[[files]]
path = "Content.Shared/_CD/**"
license = "MIT"

[[files]]
path = "Resources/_CD/**"
license = "MIT"

[[files]]
path = "Resources/Prototypes/_CD/**"
license = "MIT"

## DV (Delta-V) code licensed under AGPL-3.0-or-later
[[files]]
path = "Content.Server/_DV/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Client/_DV/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Shared/_DV/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/_DV/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/Prototypes/_DV/**"
license = "AGPL-3.0-or-later"

## NF (Frontier) code licensed under MIT
[[files]]
path = "Content.Server/_NF/**"
license = "MIT"

[[files]]
path = "Content.Client/_NF/**"
license = "MIT"

[[files]]
path = "Content.Shared/_NF/**"
license = "MIT"

[[files]]
path = "Resources/_NF/**"
license = "MIT"

[[files]]
path = "Resources/Prototypes/_NF/**"
license = "MIT"

## Harmony code licensed under AGPL-3.0-or-later
[[files]]
path = "Content.Server/_Harmony/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Client/_Harmony/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Shared/_Harmony/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/_Harmony/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/Prototypes/_Harmony/**"
license = "AGPL-3.0-or-later"

## Umbra code licensed under MIT
[[files]]
path = "Content.Server/_Umbra/**"
license = "MIT"

[[files]]
path = "Content.Client/_Umbra/**"
license = "MIT"

[[files]]
path = "Content.Shared/_Umbra/**"
license = "MIT"

[[files]]
path = "Resources/_Umbra/**"
license = "MIT"

[[files]]
path = "Resources/Prototypes/_Umbra/**"
license = "MIT"

## Floofstation code licensed under AGPL-3.0-or-later
[[files]]
path = "Content.Server/_Floofstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Client/_Floofstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Shared/_Floofstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/_Floofstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/Prototypes/_Floofstation/**"
license = "AGPL-3.0-or-later"

## Impstation code licensed under AGPL-3.0-or-later
[[files]]
path = "Content.Server/_Impstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Client/_Impstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Shared/_Impstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/_Impstation/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/Prototypes/_Impstation/**"
license = "AGPL-3.0-or-later"

## EinsteinEngines code licensed under AGPL-3.0-or-later
[[files]]
path = "Content.Server/_EinsteinEngines/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Client/_EinsteinEngines/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Content.Shared/_EinsteinEngines/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/_EinsteinEngines/**"
license = "AGPL-3.0-or-later"

[[files]]
path = "Resources/Prototypes/_EinsteinEngines/**"
license = "AGPL-3.0-or-later"

# Textures and assets
[[files]]
path = "Resources/Textures/**"
license = "CC-BY-SA-3.0"

# Localizations
[[files]]
path = "Resources/Locale/**"
license = "MIT"

# Fallback resources default (after specific assets above)
[[files]]
path = "Resources/**"
license = "MIT"
