# SPDX-FileCopyrightText: 2022 metalgearsloth
# SPDX-FileCopyrightText: 2022 mirrorcult
# SPDX-FileCopyrightText: 2024 TsjipTsjip
# SPDX-FileCopyrightText: 2025 ReboundQ3
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Labels: PR"

on:
  pull_request_target:

jobs:
  labeler:
    if: ${{ github.actor != 'Weh-Bot' && github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo for config
        uses: actions/checkout@v4
        with:
          # Ensure we have the base repository's files locally (for config path)
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 1
          persist-credentials: false
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
          # Use repository-scoped token so label creation respects base repo permissions
          repo-token: ${{ secrets.GITHUB_TOKEN }}
