## SPDX-License-Identifier: AGPL-3.0-or-later

name: Update REUSE Headers

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**/*.cs'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.py'
      - '.reuse/**'
      - 'REUSE.toml'
      - 'LICENSES/**'
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GH_TOKEN: ${{ github.token }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REUSE_LICENSE_MAP_PATH: .reuse/path-licenses.json

concurrency:
  group: reuse-updater-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update_headers:
    if: ${{ github.actor != 'PJBot' && github.actor != 'weh-bot' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout PR head (pull_request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout base repo (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Git identity
        run: |
          git config --global user.name "weh-bot"
          git config --global user.email "weh-bot@users.noreply.github.com"
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
        shell: bash

      - name: Get Changed Files and PR Info
        id: changed_files
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: |
          set -euo pipefail
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"

          echo "Fetching files for PR #${PR_NUMBER} in repo ${GH_REPO}"
          PR_FILES=""
          PAGE=1
          while true; do
            PAGE_JSON=$(curl -s -f -H "Authorization: token ${GH_TOKEN}" "https://api.github.com/repos/${GH_REPO}/pulls/${PR_NUMBER}/files?per_page=100&page=${PAGE}") || true
            if [ -z "${PAGE_JSON}" ] || ! echo "${PAGE_JSON}" | jq -e . >/dev/null 2>&1; then
              break
            fi
            PAGE_COUNT=$(echo "${PAGE_JSON}" | jq 'length')
            if [ "${PAGE_COUNT}" -eq 0 ] 2>/dev/null; then
              break
            fi
            PAGE_LINES=$(echo "${PAGE_JSON}" | jq -r '.[] | select(.filename != null) | "\(.status) \(.filename)"')
            PR_FILES=$(printf "%s\n%s\n" "${PR_FILES}" "${PAGE_LINES}")
            PAGE=$((PAGE+1))
          done

          PR_FILES=$(echo "${PR_FILES}" | sed '/^$/d')

          echo "API reported files (status path):"
          echo "${PR_FILES}" | sed 's/^/  /' || true

          if [ "${GITHUB_EVENT_NAME}" = "pull_request_target" ]; then
            git remote add fork "https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git" || true
            git fetch --no-tags --prune --depth=0 fork "${{ github.event.pull_request.head.ref }}:pr-head"
            DIFF_LINES=$(git diff --name-status "${{ github.event.pull_request.base.sha }}" pr-head | sed 's/^\t\+/\t/g' | awk '{s=$1; $1=""; sub(/^\s+/, ""); print tolower(s)" "$0}') | sed '/^$/d' || true
          else
            DIFF_LINES=$(git diff --name-status "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}" | sed 's/^\t\+/\t/g' | awk '{s=$1; $1=""; sub(/^\s+/, ""); print tolower(s)" "$0}') | sed '/^$/d' || true
          fi

          if [ -n "${DIFF_LINES}" ]; then
            echo "git diff reported files (status path):"
            echo "${DIFF_LINES}" | sed 's/^/  /'
            PR_FILES=$(printf "%s\n%s\n" "${PR_FILES}" "${DIFF_LINES}")
          fi

          PR_FILES=$(echo "${PR_FILES}" | sed '/^$/d' | sort -u)

          if [ -z "$PR_FILES" ]; then
            ADDED_FILES=""
            MODIFIED_FILES=""
          else
            ADDED_FILES=$(echo "$PR_FILES" | awk '{ s=tolower($1); $1=""; sub(/^\s+/, ""); p=$0; lp=tolower(p); if ((s=="added" || s=="a") && lp ~ /\.(cs|yml|yaml|py)$/) print p }' | xargs) || true
            MODIFIED_FILES=$(echo "$PR_FILES" | awk '{ s=tolower($1); $1=""; sub(/^\s+/, ""); p=$0; lp=tolower(p); if ((s=="modified" || s=="m" || s=="renamed" || s=="copied" || s=="changed") && lp ~ /\.(cs|yml|yaml|py)$/) print p }' | xargs) || true
          fi

          echo "Added Files: $ADDED_FILES"
          echo "Modified Files: $MODIFIED_FILES"

          {
            echo "added<<EOF";
            echo "$ADDED_FILES";
            echo "EOF";
            echo "modified<<EOF";
            echo "$MODIFIED_FILES";
            echo "EOF";
          } >> $GITHUB_OUTPUT

          if grep -q "LICENSE: MIT" <<< "$PR_BODY"; then
            echo "PR_LICENSE=mit" >> $GITHUB_ENV
          elif grep -q "LICENSE: AGPL" <<< "$PR_BODY"; then
            echo "PR_LICENSE=agpl" >> $GITHUB_ENV
          elif grep -q "LICENSE: MPL" <<< "$PR_BODY"; then
            echo "PR_LICENSE=mpl" >> $GITHUB_ENV
          else
            echo "PR_LICENSE=agpl" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Skip if no relevant files changed
        if: ${{ steps.changed_files.outputs.added == '' && steps.changed_files.outputs.modified == '' }}
        run: echo "No relevant .cs/.yml/.yaml/.py changes detected; skipping header update."
        shell: bash

      - name: Prepare PR worktree (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' && (steps.changed_files.outputs.added != '' || steps.changed_files.outputs.modified != '') }}
        run: |
          git worktree add _prwork pr-head
          mkdir -p /tmp/reuse
          cp Tools/update_pr_reuse_headers.py /tmp/reuse/updater.py
        shell: bash

      - name: Run REUSE Header Update Script (pull_request)
        if: ${{ github.event_name == 'pull_request' && (steps.changed_files.outputs.added != '' || steps.changed_files.outputs.modified != '') }}
        run: |
          python Tools/update_pr_reuse_headers.py \
            --files-added "${{ steps.changed_files.outputs.added }}" \
            --files-modified "${{ steps.changed_files.outputs.modified }}" \
            --pr-license "$PR_LICENSE" \
            --pr-base-sha ${{ github.event.pull_request.base.sha }} \
            --pr-head-sha ${{ github.event.pull_request.head.sha }} \
            --pr-author ${{ github.event.pull_request.user.login }}
        working-directory: ${{ github.workspace }}
        shell: bash

      - name: Run REUSE Header Update Script (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' && (steps.changed_files.outputs.added != '' || steps.changed_files.outputs.modified != '') }}
        run: |
          PYTHONPATH="" python /tmp/reuse/updater.py \
            --files-added "${{ steps.changed_files.outputs.added }}" \
            --files-modified "${{ steps.changed_files.outputs.modified }}" \
            --pr-license "$PR_LICENSE" \
            --pr-base-sha ${{ github.event.pull_request.base.sha }} \
            --pr-head-sha ${{ github.event.pull_request.head.sha }} \
            --pr-author ${{ github.event.pull_request.user.login }}
        working-directory: _prwork
        shell: bash

      - name: Commit changes
        if: ${{ steps.changed_files.outputs.added != '' || steps.changed_files.outputs.modified != '' }}
        id: commit
        run: |
          if [ -d _prwork ]; then cd _prwork; fi
          git add -A
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          git commit -m "chore(reuse): update REUSE headers (#$PR_NUMBER)"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        shell: bash

      - name: Push changes (same-repo PRs)
        if: ${{ steps.commit.outputs.has_changes == 'true' && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.event.pull_request.head.repo.full_name }}.git" "HEAD:${{ github.event.pull_request.head.ref }}"
        shell: bash

      - name: Push changes (fork PRs via bot token)
        if: ${{ steps.commit.outputs.has_changes == 'true' && github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository }}
        env:
          BOT_PAT: ${{ secrets.WEH_BOT_PAT }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          cd _prwork
          if [ -z "${BOT_PAT}" ]; then
            echo "Missing WEH_BOT_PAT secret; cannot push to fork automatically." >&2
            exit 1
          fi
          git push "https://x-access-token:${BOT_PAT}@github.com/${HEAD_REPO}.git" "HEAD:${HEAD_REF}"
        shell: bash
